stages:
  download_v1:
    cmd: python scripts/download_asset_v1.py
    deps:
      - scripts/download_asset_v1.py
    outs:
      - data/raw/mnist_x_train_v1.npy
      - data/raw/mnist_y_train_v1.npy
      - data/raw/mnist_x_test_v1.npy
      - data/raw/mnist_y_test_v1.npy

  download_v2:
    cmd: python scripts/download_asset_v2.py
    deps:
      - scripts/download_asset_v2.py
      - data/raw/mnist_x_train_v1.npy
      - data/raw/mnist_y_train_v1.npy
    outs:
      - data/raw/mnist_x_train_v2.npy
      - data/raw/mnist_y_train_v2.npy

  train_v1:
    cmd: python scripts/train.py --version v1
    deps:
      - scripts/train.py
      - data/raw/mnist_x_train_v1.npy
      - data/raw/mnist_y_train_v1.npy
      - data/raw/mnist_x_test_v1.npy
      - data/raw/mnist_y_test_v1.npy
    outs:
      - models/rf_mnist_v1.npy
    metrics:
      - models/metrics_v1.json:
          cache: false

  train_v2:
    cmd: python scripts/train.py --version v2
    deps:
      - scripts/train.py
      - data/raw/mnist_x_train_v2.npy
      - data/raw/mnist_y_train_v2.npy
      - data/raw/mnist_x_test_v1.npy
      - data/raw/mnist_y_test_v1.npy
    outs:
      - models/rf_mnist_v2.npy
    metrics:
      - models/metrics_v2.json:
          cache: false
plots:
  - epoch vs loss:
      template: simple
      x: epoch
      y:
        data/raw/loss.csv: loss
